// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxiMfm8XrpoM1izbDhtnvqyd5b6kb-ZuA',
    appId: '1:348220211265:android:6027839b6d30ac978c06c0',
    messagingSenderId: '348220211265',
    projectId: 'bloomin-dfaac',
    databaseURL: 'https://bloomin-dfaac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloomin-dfaac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBrfZZqz6yogdGnkjjLBzFMbzKWEAFVGE',
    appId: '1:348220211265:ios:4d1f85225e34293a8c06c0',
    messagingSenderId: '348220211265',
    projectId: 'bloomin-dfaac',
    databaseURL: 'https://bloomin-dfaac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloomin-dfaac.firebasestorage.app',
    iosBundleId: 'com.example.bloomin',
  );
}
